site_name: ""
site_url: https://docshopfono.github.io/CanetaForma/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: pt-BR

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css

nav:
  - Início (Português): index.md
  - English: en-US/README.md
  - Español: es-ES/README.md

