site_name: Manual Extensor Caneta FORMA - ShopFONO
site_url: https://carlosshopfono.github.io/CanetaForma/

theme:
  name: material
  language: pt-BR

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav:
  - Início: README.md
  - Português: pt-BR/README.md
  - English: en-US/README.md
  - Español: es-ES/README.md

